---
# http://docs.ansible.com/ansible/galaxy.html
- src: geerlingguy.repo-epel
- src: geerlingguy.pip
- src: carlba.gitconfig
  version: master
- src: carlba.bash_aliases
- src: carlba.vim
  version: master
- src: carlba.tmux
  version: master
