---

- name: Ensure passwordless sudo is enabled for current user
  become: true
  blockinfile:
    dest: "/etc/sudoers.d/dotfiles"
    block: "{{ ansible_env.USER }} ALL=(ALL) ALL"
    create: true
  when: is_privileged_user

- include: macos.yml
  when: ansible_os_family in ['Darwin']

- name: Ensure apt cache is updated on Debian based OSes
  become: true
  apt: update_cache=true cache_valid_time=3600
  when: is_privileged_user and ansible_os_family == 'Debian'

- name: Ensure base dependencies are installed
  become: "{{ (ansible_os_family in ['Darwin']) | ternary('false', 'true') }}"
  package: name={{item}}
  with_items:
    - git
    - jq
    - htop
    - wget
    - bash-completion
    - man
  when: is_privileged_user

# https://sanctum.geek.nz/arabesque/better-bash-history/
- name: 'Ensure improved bash history is applied to "{{ ansible_env.HOME }}/.bashrc"'
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK (better bash history)"
    block: |
      HISTFILESIZE=1000000
      HISTSIZE=1000000
      HISTCONTROL=ignoreboth
      HISTTIMEFORMAT='%Y-%m-%dT%T '
      shopt -s cmdhist
      shopt -s histappend

- name: 'Ensure bash color theme is applied to "{{ ansible_env.HOME }}/.bashrc"'
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK (add colors in terminal)"
    block: |
      function parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }
      function EXT_COLOR () { echo -ne "\e[38;5;$1m"; }
      function CLOSE_COLOR () { echo -ne '\e[m'; }
      export PS1="\[`EXT_COLOR 187`\]\u@\h\[`CLOSE_COLOR`\]\[`EXT_COLOR 174`\] \w\$(parse_git_branch) \$ \[`CLOSE_COLOR`\]"
      export LS_COLORS='di=38;5;108:fi=00:*svn-commit.tmp=31:ln=38;5;116:ex=38;5;186'
